# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('a7be69e68b6c13aaf1d2bf7f52325093_OTQ0NDEyMDEyLTA1LTI4IDIwOjAyOjEwLjM1NDE0NQ')
  end)
end
